package My.DomoticRoomVistaControlador;
//
import My.DomoticRoomModelo.ListaLuces;
import My.DomoticRoomModelo.Luz;
import java.awt.Color;
import java.awt.Toolkit;

/**
 * Clase DomoticRoomUI
 * 
 * @author Jorge Barrio Conde
 * @author Miguel de la Parte Florez
 **/
public class DomoticRoomUI extends javax.swing.JFrame {
    private final static int DESPL = 3;
    private DomoticRoomControlador miControl;
    private Luz luz;
    private Color colorBotones;
    /**
     * Inicializador DomoticRoomUI
     **/
    public DomoticRoomUI() {
        initComponents();
        luz = new Luz("nombre");
        miControl = new DomoticRoomControlador(this,luz);
        barraDeIntensidad.setMaximum(100);
        barraDeIntensidad.setMinimum(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSeleccion = new javax.swing.JPanel();
        botonLamparaSillon = new javax.swing.JButton();
        botonLamparaCamaR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonLamparaCamaL = new javax.swing.JButton();
        botonLamparaDesk = new javax.swing.JButton();
        botonLamparaGeneral = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelConfiguracion = new javax.swing.JPanel();
        barraDeIntensidad = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        selectorDeColor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        interruptor = new javax.swing.JButton();
        identificadorDeLuz = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelModos = new javax.swing.JPanel();
        botonTodoEncendido = new javax.swing.JButton();
        botonTodoApagado = new javax.swing.JButton();
        botonAmbiente = new javax.swing.JButton();
        botonLectura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(1016, 600));

        panelSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion de luz"));

        botonLamparaSillon.setBackground(java.awt.Color.white);
        botonLamparaSillon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Sillon/sillonOff.png"))); // NOI18N
        botonLamparaSillon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLamparaSillon.setMinimumSize(new java.awt.Dimension(120, 130));
        botonLamparaSillon.setPreferredSize(new java.awt.Dimension(125, 133));
        botonLamparaSillon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLamparaSillonActionPerformed(evt);
            }
        });

        botonLamparaCamaR.setBackground(java.awt.Color.white);
        botonLamparaCamaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedR/bedROff.png"))); // NOI18N
        botonLamparaCamaR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLamparaCamaR.setPreferredSize(new java.awt.Dimension(125, 133));
        botonLamparaCamaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLamparaCamaRActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/roomRIGHT.png"))); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/roomLEFT.png"))); // NOI18N

        botonLamparaCamaL.setBackground(java.awt.Color.red);
        botonLamparaCamaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedL/bedLOff.png"))); // NOI18N
        botonLamparaCamaL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLamparaCamaL.setMinimumSize(new java.awt.Dimension(120, 130));
        botonLamparaCamaL.setPreferredSize(new java.awt.Dimension(125, 133));
        botonLamparaCamaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLamparaCamaLActionPerformed(evt);
            }
        });

        botonLamparaDesk.setBackground(java.awt.Color.white);
        botonLamparaDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Desk/deskOff.png"))); // NOI18N
        botonLamparaDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLamparaDesk.setMinimumSize(new java.awt.Dimension(120, 130));
        botonLamparaDesk.setPreferredSize(new java.awt.Dimension(125, 133));
        botonLamparaDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLamparaDeskActionPerformed(evt);
            }
        });

        botonLamparaGeneral.setBackground(java.awt.Color.white);
        botonLamparaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/General/generalOff.png"))); // NOI18N
        botonLamparaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLamparaGeneral.setPreferredSize(new java.awt.Dimension(101, 60));
        botonLamparaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLamparaGeneralActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/roomUP.png"))); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/roomDOWN.png"))); // NOI18N

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLamparaCamaL, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLamparaDesk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLamparaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSeleccionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonLamparaSillon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(botonLamparaCamaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLamparaCamaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLamparaCamaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLamparaSillon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(botonLamparaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLamparaDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panelConfiguracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Control de intensidad"));
        panelConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        barraDeIntensidad.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        barraDeIntensidad.setMajorTickSpacing(10);
        barraDeIntensidad.setMinorTickSpacing(10);
        barraDeIntensidad.setPaintLabels(true);
        barraDeIntensidad.setPaintTicks(true);
        barraDeIntensidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraDeIntensidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraDeIntensidadStateChanged(evt);
            }
        });

        jLabel1.setText("Intensidad");

        selectorDeColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Amarillo", "Verde", "Rojo", "Azul" }));
        selectorDeColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectorDeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorDeColorActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Color");

        interruptor.setBackground(java.awt.Color.white);
        interruptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/OFF.png"))); // NOI18N
        interruptor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        interruptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interruptorActionPerformed(evt);
            }
        });

        identificadorDeLuz.setText("Indentificador de luz");

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificadorDeLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                                .addComponent(selectorDeColor, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(barraDeIntensidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interruptor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(identificadorDeLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel20))
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(interruptor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfiguracionLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfiguracionLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(barraDeIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectorDeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        panelModos.setBorder(javax.swing.BorderFactory.createTitledBorder("Modos de seleccion"));

        botonTodoEncendido.setBackground(new java.awt.Color(254, 254, 254));
        botonTodoEncendido.setText("Todo encendido");
        botonTodoEncendido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTodoEncendido.setPreferredSize(new java.awt.Dimension(124, 30));
        botonTodoEncendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTodoEncendidoActionPerformed(evt);
            }
        });

        botonTodoApagado.setBackground(new java.awt.Color(254, 254, 254));
        botonTodoApagado.setText("Todo apagado");
        botonTodoApagado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTodoApagado.setPreferredSize(new java.awt.Dimension(125, 30));
        botonTodoApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTodoApagadoActionPerformed(evt);
            }
        });

        botonAmbiente.setBackground(new java.awt.Color(254, 254, 254));
        botonAmbiente.setText("Ambiente");
        botonAmbiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAmbiente.setPreferredSize(new java.awt.Dimension(125, 30));
        botonAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAmbienteActionPerformed(evt);
            }
        });

        botonLectura.setBackground(new java.awt.Color(254, 254, 254));
        botonLectura.setText("Lectura");
        botonLectura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLectura.setPreferredSize(new java.awt.Dimension(223, 30));
        botonLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLecturaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Todas la luces estaran encendidas");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Todas las luces estaran apagadas");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Todas la luces estaran encendidas de"); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setMinimumSize(new java.awt.Dimension(224, 0));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("color amarillo y al 30% de intensidad");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Solo la luz 1 y 3 estaran encendidas, de"); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setMinimumSize(new java.awt.Dimension(224, 0));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("color blanco y al 60% de intensidad");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelModosLayout = new javax.swing.GroupLayout(panelModos);
        panelModos.setLayout(panelModosLayout);
        panelModosLayout.setHorizontalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTodoEncendido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonTodoApagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonLectura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelModosLayout.setVerticalGroup(
            panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModosLayout.createSequentialGroup()
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonTodoEncendido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTodoApagado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAmbiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonLectura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)))
        );

        panelTitulo.setBackground(new java.awt.Color(48, 48, 48));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Iluminacion");

        botonVolver.setBackground(new java.awt.Color(48, 48, 48));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/volver.png"))); // NOI18N
        botonVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Control de la iluminacion del salon del hogar");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelModos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelModos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorDeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDeColorActionPerformed
        miControl.caja(selectorDeColor.getSelectedIndex());
    }//GEN-LAST:event_selectorDeColorActionPerformed
    /**
     * Actualiza la vista de los paneles inferiores
     * @param num Intensidad
     * @param pos Color
     * @param estado Encendido/apagado
     */
    public void actualizarVista(int num, int pos, boolean estado){
        barraDeIntensidad.setValue(num);
        selectorDeColor.setSelectedIndex(pos);
        if (estado){
            interruptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/ON.png")));
            
        }else{
            interruptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/OFF.png")));
        }
        if(miControl.getLista().getLuz("bedL").getEstado())
            botonLamparaCamaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedL/bedL"+miControl.getColor("botonLamparaCamaL")+".png")));
        else
            botonLamparaCamaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedL/bedLOff.png")));
        if(miControl.getLista().getLuz("bedR").getEstado())
            botonLamparaCamaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedR/bedR"+miControl.getColor("botonLamparaCamaR")+".png")));
        else
            botonLamparaCamaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/BedR/bedROff.png")));
            
        if(miControl.getLista().getLuz("general").getEstado())
        botonLamparaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/General/general"+miControl.getColor("botonLamparaGeneral")+".png")));
        else
            botonLamparaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/General/generalOff.png")));
        if(miControl.getLista().getLuz("desk").getEstado())
            botonLamparaDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Desk/desk"+miControl.getColor("botonLamparaDesk")+".png")));
        else
            botonLamparaDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Desk/deskOff.png")));
        if(miControl.getLista().getLuz("sillon").getEstado())
            botonLamparaSillon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Sillon/sillon"+miControl.getColor("botonLamparaSillon")+".png")));
        else
            botonLamparaSillon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Lamparas/Sillon/sillonOff.png")));
        
        }
    /**
     * Conmuta  el boton de todo encendido
     */
    public void switchEncendido(){
        if (botonTodoEncendido.getBackground().equals(new Color(102,255,102))){
            botonTodoEncendido.setBackground(new Color(240,240,240));
        }
        else{
            botonTodoEncendido.setBackground(new Color(102,255,102));
            botonTodoApagado.setBackground(new Color(240,240,240));
            botonLectura.setBackground(new Color(240,240,240));
            botonAmbiente.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Cambia el boton de todo encendido en funcion de un booleano
     */
    public void switchEncendido(boolean valor){
        if (valor){
            botonTodoEncendido.setBackground(new Color(102,255,102));
        }else{
            botonTodoEncendido.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de todo Apagado
     */
    public void switchApagado(){
        if (botonTodoApagado.getBackground().equals(new Color(102,255,102)))
            botonTodoApagado.setBackground(new Color(240,240,240));
        else{
            botonTodoApagado.setBackground(new Color(102,255,102));
            botonTodoEncendido.setBackground(new Color(240,240,240));
            botonLectura.setBackground(new Color(240,240,240));
            botonAmbiente.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de todo Apagado en funion de un booleano
     */
    public void switchApagado(boolean valor){
        if (valor){
            botonTodoApagado.setBackground(new Color(102,255,102));
        }else{
            botonTodoApagado.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de Lectura
     */
    public void switchLectura(){
        if (botonLectura.getBackground().equals(new Color(102,255,102)))
            botonLectura.setBackground(new Color(240,240,240));
        else{
            botonLectura.setBackground(new Color(102,255,102));
            botonTodoEncendido.setBackground(new Color(240,240,240));
            botonTodoApagado.setBackground(new Color(240,240,240));
            botonAmbiente.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de Lectura en funcion a un booleano
     */
    public void switchLectura(boolean valor){
        if (valor){
            botonLectura.setBackground(new Color(102,255,102));
        }else{
            botonLectura.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de Ambiente
     */
    public void switchAmbiente(){
        if (botonAmbiente.getBackground().equals(new Color(102,255,102)))
            botonAmbiente.setBackground(new Color(240,240,240));
        else{
            botonAmbiente.setBackground(new Color(102,255,102));
            botonTodoEncendido.setBackground(new Color(240,240,240));
            botonTodoApagado.setBackground(new Color(240,240,240));
            botonLectura.setBackground(new Color(240,240,240));
        }
    }
    /**
     * Conmuta el boton de Ambiente en funcion a un booleano
     */
    public void switchAmbiente(boolean valor){
        if (valor){
            botonAmbiente.setBackground(new Color(102,255,102));
        }else{
            botonAmbiente.setBackground(new Color(240,240,240));
        }
    }

    /**
     * Cambia el color de los botones segun un color dado
     * @param color el color a cambiar
     */
    public void setColorBotones(Color color){
        colorBotones = Color.WHITE;
    }
    /**
    * Establece un color rojo al boton de la Luz seleccionada
    * @param a 
    */
    public void botonSeleccionado (javax.swing.JButton a){
        a.setBackground(Color.red);
    }
    public void botonesPorDefecto (){
        botonLamparaDesk.setBackground(colorBotones);
        botonLamparaGeneral.setBackground(colorBotones);
        botonLamparaCamaL.setBackground(colorBotones);
        botonLamparaCamaR.setBackground(colorBotones);
        botonLamparaSillon.setBackground(colorBotones);   
    }
    private void interruptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interruptorActionPerformed
        miControl.interruptor();
    }//GEN-LAST:event_interruptorActionPerformed

    private void barraDeIntensidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraDeIntensidadStateChanged
        miControl.barra(barraDeIntensidad.getValue());
    }//GEN-LAST:event_barraDeIntensidadStateChanged

    private void botonTodoEncendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTodoEncendidoActionPerformed
        miControl.encendido();
    }//GEN-LAST:event_botonTodoEncendidoActionPerformed

    private void botonTodoApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTodoApagadoActionPerformed
        miControl.apagado();
    }//GEN-LAST:event_botonTodoApagadoActionPerformed

    private void botonAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmbienteActionPerformed
        miControl.ambiental();
    }//GEN-LAST:event_botonAmbienteActionPerformed

    private void botonLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLecturaActionPerformed
        miControl.lectura();
    }//GEN-LAST:event_botonLecturaActionPerformed

    private void botonLamparaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLamparaGeneralActionPerformed
        miControl.ctrboton(botonLamparaGeneral);
    }//GEN-LAST:event_botonLamparaGeneralActionPerformed

    private void botonLamparaDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLamparaDeskActionPerformed
        miControl.blboton(botonLamparaDesk);
    }//GEN-LAST:event_botonLamparaDeskActionPerformed

    private void botonLamparaCamaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLamparaCamaLActionPerformed
        miControl.tlboton(botonLamparaCamaL);
    }//GEN-LAST:event_botonLamparaCamaLActionPerformed

    private void botonLamparaCamaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLamparaCamaRActionPerformed
        miControl.trboton(botonLamparaCamaR);
    }//GEN-LAST:event_botonLamparaCamaRActionPerformed

    private void botonLamparaSillonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLamparaSillonActionPerformed
        miControl.brboton(botonLamparaSillon);
    }//GEN-LAST:event_botonLamparaSillonActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        miControl.back();
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barraDeIntensidad;
    private javax.swing.JButton botonAmbiente;
    private javax.swing.JButton botonLamparaCamaL;
    private javax.swing.JButton botonLamparaCamaR;
    private javax.swing.JButton botonLamparaDesk;
    private javax.swing.JButton botonLamparaGeneral;
    private javax.swing.JButton botonLamparaSillon;
    private javax.swing.JButton botonLectura;
    private javax.swing.JButton botonTodoApagado;
    private javax.swing.JButton botonTodoEncendido;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel identificadorDeLuz;
    private javax.swing.JButton interruptor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelModos;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JComboBox<String> selectorDeColor;
    // End of variables declaration//GEN-END:variables
}
