package My.DomoticRoomVistaControlador;

import My.DomoticRoom.Main;
import My.DomoticRoomModelo.*;
import java.text.DecimalFormat;

/**
 * Clase General
 * @author Jorge Barrio Conde
 * @author Miguel de la Parte Florez
 */

public class General extends javax.swing.JFrame {
    private GeneralControlador miControl;

    public static ListaLuces listaLuces = new ListaLuces();
    
    DecimalFormat formato = new DecimalFormat("#.0");

    /**
     * Inicializador de General
     */
    public General() {

        initComponents();

        miControl = new GeneralControlador(this);
        
        actualizaInfor();
        initializeRepresentaTemp();
    }

    public void actualizaInfor(){
        labelTempDeseada.setText(formato.format((Main.getCalefaccionModelo()).getTemperaturaDeseada()));
        
        labelNumLucesEncendidas.setText(""+Main.getListaLuces().cuantasEncendidas());
        
        if((Main.getListaLuces()).checkApagado()) labelBombilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/bombillaOff.png")));
        else labelBombilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/bombillaOn.png")));
        
        if((Main.getCalefaccionModelo()).getEncendido()) labelCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/wradiadorOn105.png")));
        else labelCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/wradiadorOff105.png")));
        
        System.out.println((Main.getPersianaModelo()).getPersiana1()+" & "+(Main.getPersianaModelo()).getPersiana2());
        
        if(!(Main.getPersianaModelo()).getPersiana1() && !(Main.getPersianaModelo()).getPersiana2()) 
            labelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/casaEdit00.png")));
        else if(!(Main.getPersianaModelo()).getPersiana1() && (Main.getPersianaModelo()).getPersiana2()) 
            labelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/casaEdit10.png")));
        else if((Main.getPersianaModelo()).getPersiana1() && !(Main.getPersianaModelo()).getPersiana2()) 
            labelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/casaEdit01.png")));
        else if((Main.getPersianaModelo()).getPersiana1() && (Main.getPersianaModelo()).getPersiana2()) 
            labelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/casaEdit11.png")));
    }

    /**
     * Reloj que va decrementando la temperaturaActual
     */
    private void initializeRepresentaTemp() {
        new Thread() {
            @Override
            public void run() {
                while(true){
                    labelTempActual.setText(formato.format((Main.getCalefaccionModelo()).getTemperaturaActual()));
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonIluminacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        panelRepresentacion = new javax.swing.JPanel();
        panelCasa = new javax.swing.JPanel();
        labelCasa = new javax.swing.JLabel();
        panelValores = new javax.swing.JPanel();
        labelTempActual = new javax.swing.JLabel();
        labelTempDeseada = new javax.swing.JLabel();
        labelCalefaccion = new javax.swing.JLabel();
        labelExplicaTempActual = new javax.swing.JLabel();
        labelExplicaTempActual1 = new javax.swing.JLabel();
        labelBombilla = new javax.swing.JLabel();
        labelExplicaLuz = new javax.swing.JLabel();
        labelExplicaLuz2 = new javax.swing.JLabel();
        labelNumLucesEncendidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(48, 48, 48));
        panelFondo.setPreferredSize(new java.awt.Dimension(1016, 600));

        panelBotones.setBackground(new java.awt.Color(48, 48, 48));

        botonIluminacion.setBackground(new java.awt.Color(254, 254, 254));
        botonIluminacion.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        botonIluminacion.setForeground(new java.awt.Color(1, 1, 1));
        botonIluminacion.setText("ILUMINACION");
        botonIluminacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIluminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIluminacionActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setText("CALEFACCION");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(1, 1, 1));
        jButton3.setText("PERSIANAS");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonIluminacion, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        panelTitulo.setBackground(new java.awt.Color(48, 48, 48));

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 72)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(254, 254, 254));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("iHOME");

        labelDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(254, 254, 254));
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescripcion.setText("Controlador de la instalacion domotica de su hogar");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );

        panelRepresentacion.setBackground(new java.awt.Color(48, 48, 48));

        panelCasa.setBackground(new java.awt.Color(48, 48, 48));

        labelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/wcasaEdit00.png"))); // NOI18N

        javax.swing.GroupLayout panelCasaLayout = new javax.swing.GroupLayout(panelCasa);
        panelCasa.setLayout(panelCasaLayout);
        panelCasaLayout.setHorizontalGroup(
            panelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCasa)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelCasaLayout.setVerticalGroup(
            panelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCasaLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(labelCasa)
                .addGap(34, 34, 34))
        );

        panelValores.setBackground(new java.awt.Color(48, 48, 48));

        labelTempActual.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTempActual.setForeground(new java.awt.Color(255, 255, 255));
        labelTempActual.setText("20,0");

        labelTempDeseada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTempDeseada.setForeground(new java.awt.Color(255, 255, 255));
        labelTempDeseada.setText("21,0");

        labelCalefaccion.setBackground(new java.awt.Color(255, 128, 0));

        labelExplicaTempActual.setForeground(new java.awt.Color(254, 254, 254));
        labelExplicaTempActual.setText("Temperatura");

        labelExplicaTempActual1.setForeground(new java.awt.Color(254, 254, 254));
        labelExplicaTempActual1.setText("actual:");

        labelExplicaLuz.setForeground(new java.awt.Color(254, 254, 254));
        labelExplicaLuz.setText("Luces");

        labelExplicaLuz2.setForeground(new java.awt.Color(254, 254, 254));
        labelExplicaLuz2.setText("encendidas:");

        labelNumLucesEncendidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNumLucesEncendidas.setForeground(new java.awt.Color(255, 255, 255));
        labelNumLucesEncendidas.setText("0");

        javax.swing.GroupLayout panelValoresLayout = new javax.swing.GroupLayout(panelValores);
        panelValores.setLayout(panelValoresLayout);
        panelValoresLayout.setHorizontalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addComponent(labelBombilla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumLucesEncendidas)
                    .addComponent(labelExplicaLuz)
                    .addComponent(labelExplicaLuz2))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelValoresLayout.createSequentialGroup()
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addComponent(labelCalefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTempActual)
                            .addComponent(labelExplicaTempActual)
                            .addComponent(labelExplicaTempActual1)))
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelTempDeseada)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelValoresLayout.setVerticalGroup(
            panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBombilla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExplicaLuz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExplicaLuz2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNumLucesEncendidas)
                        .addGap(16, 16, 16)))
                .addGap(59, 59, 59)
                .addGroup(panelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCalefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelValoresLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelExplicaTempActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExplicaTempActual1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTempActual)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTempDeseada)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout panelRepresentacionLayout = new javax.swing.GroupLayout(panelRepresentacion);
        panelRepresentacion.setLayout(panelRepresentacionLayout);
        panelRepresentacionLayout.setHorizontalGroup(
            panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRepresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRepresentacionLayout.setVerticalGroup(
            panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRepresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRepresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRepresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        miControl.calefaccionOn();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        miControl.persianaOn();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonIluminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIluminacionActionPerformed
        miControl.lucesOn();
    }//GEN-LAST:event_botonIluminacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIluminacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel labelBombilla;
    private javax.swing.JLabel labelCalefaccion;
    private javax.swing.JLabel labelCasa;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelExplicaLuz;
    private javax.swing.JLabel labelExplicaLuz2;
    private javax.swing.JLabel labelExplicaTempActual;
    private javax.swing.JLabel labelExplicaTempActual1;
    private javax.swing.JLabel labelNumLucesEncendidas;
    private javax.swing.JLabel labelTempActual;
    private javax.swing.JLabel labelTempDeseada;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCasa;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelRepresentacion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelValores;
    // End of variables declaration//GEN-END:variables
}
