package My.DomoticRoomVistaControlador;

import My.DomoticRoomModelo.*;
import My.DomoticRoom.Main;
import java.awt.Color;
/**
 * Clase Persiana
 *
 * @author Jorge Barrio Conde
 * @author Miguel de la Parte Florez
 */
public class Persianas extends javax.swing.JFrame {

    private PersianasControlador miControl;

    /**
     * Inicializador de la Persianas
     */
    public Persianas() {
        initComponents();
        miControl = new PersianasControlador(this);
        miControl.persiana1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        panelRepresentacion = new javax.swing.JPanel();
        panelCasa = new javax.swing.JPanel();
        botonPersiana2 = new javax.swing.JButton();
        botonPersiana1 = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(48, 48, 48));
        panelFondo.setPreferredSize(new java.awt.Dimension(1016, 600));

        panelTitulo.setBackground(new java.awt.Color(48, 48, 48));

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(254, 254, 254));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Persianas");

        labelDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(254, 254, 254));
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescripcion.setText("Controlador de la instalacion domotica de su hogar");

        botonVolver.setBackground(new java.awt.Color(48, 48, 48));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/volver.png"))); // NOI18N
        botonVolver.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                        .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRepresentacion.setBackground(new java.awt.Color(48, 48, 48));

        panelCasa.setBackground(new java.awt.Color(48, 48, 48));

        botonPersiana2.setBackground(new java.awt.Color(48, 48, 48));
        botonPersiana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaSubidaEscalada.png"))); // NOI18N
        botonPersiana2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPersiana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersiana2ActionPerformed(evt);
            }
        });

        botonPersiana1.setBackground(new java.awt.Color(1, 1, 1));
        botonPersiana1.setForeground(new java.awt.Color(48, 48, 48));
        botonPersiana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaSubidaEscalada.png"))); // NOI18N
        botonPersiana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPersiana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersiana1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCasaLayout = new javax.swing.GroupLayout(panelCasa);
        panelCasa.setLayout(panelCasaLayout);
        panelCasaLayout.setHorizontalGroup(
            panelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCasaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botonPersiana1)
                .addGap(20, 20, 20)
                .addComponent(botonPersiana2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelCasaLayout.setVerticalGroup(
            panelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCasaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonPersiana1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(botonPersiana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(48, 48, 48));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setText("/\\");
            jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
            jButton2.setText("\\/");
            jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
            panelBotones.setLayout(panelBotonesLayout);
            panelBotonesLayout.setHorizontalGroup(
                panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                    .addContainerGap(215, Short.MAX_VALUE)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(135, 135, 135))
            );
            panelBotonesLayout.setVerticalGroup(
                panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBotonesLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(86, 86, 86))
            );

            javax.swing.GroupLayout panelRepresentacionLayout = new javax.swing.GroupLayout(panelRepresentacion);
            panelRepresentacion.setLayout(panelRepresentacionLayout);
            panelRepresentacionLayout.setHorizontalGroup(
                panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRepresentacionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panelRepresentacionLayout.setVerticalGroup(
                panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRepresentacionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelRepresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(29, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
            panelFondo.setLayout(panelFondoLayout);
            panelFondoLayout.setHorizontalGroup(
                panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRepresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            panelFondoLayout.setVerticalGroup(
                panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelRepresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botonPersiana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersiana1ActionPerformed
        miControl.persiana1();
    }//GEN-LAST:event_botonPersiana1ActionPerformed

    private void botonPersiana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersiana2ActionPerformed
        miControl.persiana2();
    }//GEN-LAST:event_botonPersiana2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        miControl.up();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        miControl.down();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        miControl.back();
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Cambia la el icono de la persiana seleccionada para indicar que se sube la persiana
     * @param n numero de la persiana que queremos subir
     */
    public void subir(int n){
        if (n==1)
            botonPersiana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaSubidaEscalada.png")));
        if (n==2)
            botonPersiana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaSubidaEscalada.png")));
    }

    /**
     * Cambia la el icono de la persiana seleccionada para indicar que se baja la persiana
     * @param n numero de la persiana que queremos bajar
     */
    public void bajar(int n){
        if (n==1)
            botonPersiana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaBajadaEscalada.png")));
        if (n==2)
            botonPersiana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/persianaBajadaEscalada.png")));
    }
    
    public void seleccionaPersiana1(){
        botonPersiana2.setBackground(Color.BLACK);
        botonPersiana1.setBackground(Color.red);
    }
    
    public void seleccionaPersiana2(){
        botonPersiana1.setBackground(Color.BLACK);
        botonPersiana2.setBackground(Color.red);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPersiana1;
    private javax.swing.JButton botonPersiana2;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCasa;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelRepresentacion;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
